"""empty message

Revision ID: 711b10d838c3
Revises: b880ef7e4c78
Create Date: 2023-03-10 22:44:41.602949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711b10d838c3'
down_revision = 'b880ef7e4c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jingdong',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='店名'),
    sa.Column('cityName', sa.String(length=255), nullable=True, comment='城市'),
    sa.Column('districtName', sa.String(length=255), nullable=True, comment='区域'),
    sa.Column('brandName', sa.String(length=255), nullable=True, comment='品牌名称'),
    sa.Column('totalComments', sa.String(length=255), nullable=True, comment='评论数'),
    sa.Column('score', sa.String(length=1000), nullable=True, comment='评分'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='lat纬度，lon经度 '),
    sa.Column('price', sa.String(length=255), nullable=True, comment='价格'),
    sa.Column('coverImageUrl', sa.String(length=255), nullable=True, comment='封面图片'),
    sa.Column('amenities', sa.String(length=255), nullable=True, comment='设施'),
    sa.Column('detailPage_url', sa.String(length=255), nullable=True, comment='详情页地址'),
    sa.Column('grade', sa.String(length=255), nullable=True, comment='星级'),
    sa.Column('checkInDate', sa.String(length=255), nullable=True, comment='入住时间'),
    sa.Column('checkOutDate', sa.String(length=255), nullable=True, comment='离开时间'),
    sa.Column('businessZoneName', sa.String(length=255), nullable=True, comment='商圈名称'),
    sa.Column('province', sa.String(length=255), nullable=True, comment='省份'),
    sa.Column('image_paths', sa.String(length=255), nullable=True, comment='图片路径'),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jingdong')
    # ### end Alembic commands ###
