"""empty message

Revision ID: 892414a8e1a9
Revises: 070b2b6d48e3
Create Date: 2023-04-01 15:07:30.099160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '892414a8e1a9'
down_revision = '070b2b6d48e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=250), nullable=False, comment='登陆ip'),
    sa.Column('login_time', sa.Integer(), nullable=True, comment='登陆时间'),
    sa.Column('logout_time', sa.Integer(), nullable=True, comment='登出时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ip',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ip_id'], ['login.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ip_id')
    )
    op.add_column('question', sa.Column('u_question', sa.String(length=250), nullable=False))
    op.drop_column('question', 'question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('question', 'u_question')
    op.drop_table('user_ip')
    op.drop_table('login')
    # ### end Alembic commands ###
