"""empty message

Revision ID: b880ef7e4c78
Revises: 
Create Date: 2023-03-08 21:41:44.522429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b880ef7e4c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=70), nullable=True),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('registerTime', sa.DateTime(), nullable=True),
    sa.Column('confirm', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
